#!/usr/bin/env bash
# Build one PDF per chapter for a lecture-notes book.
# Usage: tools/build_chapter_pdfs.sh <book_dir> [chapter_basename]
#
# For each chapters/*.tex (or only the named one), this script generates a
# tiny wrapper .tex in the book directory that reuses the main file's
# preamble verbatim and inputs just that chapter, then runs latexmk to
# produce a PDF in <book_dir>/chapter_pdfs/.
#
# The version line under each chapter heading is rendered via
# \printchapterversion{<key>} which the chapter file calls itself; the
# wrapper does not need to add it.
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 <book_dir> [chapter_basename]" >&2
  exit 2
fi

BOOK_DIR="$(cd "$1" && pwd)"
ONLY_CHAPTER="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BOOK_NAME="$(basename "$BOOK_DIR")"
MAIN_TEX="$BOOK_DIR/$BOOK_NAME.tex"
OUT_DIR="$BOOK_DIR/chapter_pdfs"

if [[ ! -f "$MAIN_TEX" ]]; then
  echo "Main file not found: $MAIN_TEX" >&2
  exit 1
fi

# Refresh chapter_versions.tex from git before building.
"$SCRIPT_DIR/update_chapter_versions.sh" "$BOOK_DIR"

# Pull the preamble out of the main .tex file: everything up to (but not
# including) \begin{document}. The wrapper reuses it verbatim so package
# loads, custom commands, and any per-book tweaks stay in sync automatically.
preamble_end_line=$(grep -n '^\\begin{document}' "$MAIN_TEX" | head -1 | cut -d: -f1)
if [[ -z "$preamble_end_line" ]]; then
  echo "Could not find \\begin{document} in $MAIN_TEX" >&2
  exit 1
fi
PREAMBLE="$(sed -n "1,$((preamble_end_line - 1))p" "$MAIN_TEX")"

# Pull bibliographystyle and bibliography lines out of the main file (if any),
# so cites resolve in the chapter PDF. Two patterns are supported:
#   (a) top-level \bibliographystyle{...} + \bibliography{<file>}
#   (b) \makestandardbackmatter{<file>} (defined in tufte.cls), in which case
#       the bib file is the macro argument; we synthesise the equivalent
#       \bibliographystyle{abbrvnat} + \bibliography{<file>} for the wrapper.
BIBSTYLE_LINE="$(grep -E '^\\bibliographystyle' "$MAIN_TEX" | head -1 || true)"
BIBLIO_LINE="$(grep -E '^\\bibliography\{' "$MAIN_TEX" | head -1 || true)"
if [[ -z "$BIBLIO_LINE" ]]; then
  BACKMATTER_BIB="$(grep -E '^\\makestandardbackmatter\{' "$MAIN_TEX" \
    | head -1 \
    | sed -E 's|^\\makestandardbackmatter\{([^}]+)\}.*|\1|' || true)"
  if [[ -n "$BACKMATTER_BIB" ]]; then
    BIBSTYLE_LINE='\bibliographystyle{abbrvnat}'
    BIBLIO_LINE="\\bibliography{${BACKMATTER_BIB}}"
  fi
fi

mkdir -p "$OUT_DIR"

build_one() {
  local chapter_file="$1"
  local base
  base="$(basename "$chapter_file" .tex)"
  if [[ -n "$ONLY_CHAPTER" && "$base" != "$ONLY_CHAPTER" ]]; then
    return 0
  fi

  local wrapper="$BOOK_DIR/_ch_${base}.tex"
  {
    echo "% Generated by tools/build_chapter_pdfs.sh -- do not edit, do not commit"
    echo "$PREAMBLE"
    echo '\begin{document}'
    echo '\mainmatter'
    echo "\\input{chapters/${base}.tex}"
    if [[ -n "$BIBSTYLE_LINE" ]]; then echo "$BIBSTYLE_LINE"; fi
    if [[ -n "$BIBLIO_LINE" ]];  then echo "$BIBLIO_LINE";  fi
    echo '\end{document}'
  } > "$wrapper"

  ( cd "$BOOK_DIR" && latexmk -pdf -interaction=nonstopmode -f \
      -outdir="chapter_pdfs" \
      "_ch_${base}.tex" >/dev/null 2>&1 ) || true

  if [[ -f "$OUT_DIR/_ch_${base}.pdf" ]]; then
    mv -f "$OUT_DIR/_ch_${base}.pdf" "$OUT_DIR/${base}.pdf"
    echo "  built  ${base}.pdf"
  else
    echo "  FAILED ${base} (see ${OUT_DIR}/_ch_${base}.log)"
  fi
}

# Only build chapters that the main .tex actually \input{}s with an
# uncommented line. A chapter commented out in the main file is skipped
# from the standalone build too. (Portable to macOS bash 3.2: no mapfile.)
ACTIVE_CHAPTERS=()
while IFS= read -r base; do
  [[ -n "$base" ]] && ACTIVE_CHAPTERS+=("$base")
done < <(
  grep -E '^[[:space:]]*\\input\{chapters/[^}]+\}' "$MAIN_TEX" \
    | sed -E 's|^[[:space:]]*\\input\{chapters/([^}]+)\}.*|\1|; s|\.tex$||'
)

# Prune stale chapter PDFs (and their build artefacts) so chapter_pdfs/
# stays in sync with what the main .tex currently inputs. Building is the
# act that decides what is published; commenting a chapter out removes it.
if [[ -d "$OUT_DIR" ]]; then
  for pdf in "$OUT_DIR"/*.pdf; do
    [[ -e "$pdf" ]] || continue
    pdf_base="$(basename "$pdf" .pdf)"
    keep=false
    for active in ${ACTIVE_CHAPTERS[@]+"${ACTIVE_CHAPTERS[@]}"}; do
      if [[ "$pdf_base" == "$active" ]]; then
        keep=true
        break
      fi
    done
    if ! $keep; then
      echo "  prune  ${pdf_base}.pdf (not active in $(basename "$MAIN_TEX"))"
      rm -f "$OUT_DIR/${pdf_base}".pdf \
            "$OUT_DIR/_ch_${pdf_base}".{log,aux,out,fls,fdb_latexmk,toc,idx,ind,ilg,bbl,blg}
    fi
  done
fi

for base in ${ACTIVE_CHAPTERS[@]+"${ACTIVE_CHAPTERS[@]}"}; do
  chapter="$BOOK_DIR/chapters/${base}.tex"
  if [[ ! -f "$chapter" ]]; then
    echo "  skip   ${base} (file not found at ${chapter})"
    continue
  fi
  build_one "$chapter"
done

# Clean up wrappers; keep the build artefacts in chapter_pdfs/ for inspection.
rm -f "$BOOK_DIR"/_ch_*.tex

echo "Done. Output in $OUT_DIR"
