#!/usr/bin/env bash
# Build a standalone PDF for a chapter that is NOT part of a published book.
# Usage: tools/build_local_pdf.sh <book_dir> <chapter_basename>
#
# Same wrapper trick as tools/build_chapter_pdfs.sh (reuse the main file's
# preamble verbatim, input a single chapter), with two differences:
#   * the chapter does not have to be \input{} by the main .tex, and
#   * the PDF lands in <book_dir>/local/ instead of <book_dir>/chapter_pdfs/.
# Both matter for unpublished material: chapter_pdfs/ is the publishing
# surface (tools/update_readme_chapters.py builds the README table from it,
# and tools/build_chapter_pdfs.sh prunes anything there that the main file
# does not input), while local/ is ignored by every publishing step.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <book_dir> <chapter_basename>" >&2
  exit 2
fi

BOOK_DIR="$(cd "$1" && pwd)"
BASE="${2%.tex}"
BOOK_NAME="$(basename "$BOOK_DIR")"
MAIN_TEX="$BOOK_DIR/$BOOK_NAME.tex"
CHAPTER="$BOOK_DIR/chapters/${BASE}.tex"
OUT_DIR="$BOOK_DIR/local"

if [[ ! -f "$MAIN_TEX" ]]; then
  echo "Main file not found: $MAIN_TEX" >&2
  exit 1
fi
if [[ ! -f "$CHAPTER" ]]; then
  echo "Chapter not found: $CHAPTER" >&2
  exit 1
fi

preamble_end_line=$(grep -n '^\\begin{document}' "$MAIN_TEX" | head -1 | cut -d: -f1)
if [[ -z "$preamble_end_line" ]]; then
  echo "Could not find \\begin{document} in $MAIN_TEX" >&2
  exit 1
fi
PREAMBLE="$(sed -n "1,$((preamble_end_line - 1))p" "$MAIN_TEX")"

# Same bibliography resolution as build_chapter_pdfs.sh: an explicit
# \bibliography{...} if the main file has one, otherwise the argument of
# \makestandardbackmatter{...}.
BIBSTYLE_LINE="$(grep -E '^\\bibliographystyle' "$MAIN_TEX" | head -1 || true)"
BIBLIO_LINE="$(grep -E '^\\bibliography\{' "$MAIN_TEX" | head -1 || true)"
if [[ -z "$BIBLIO_LINE" ]]; then
  BACKMATTER_BIB="$(grep -E '^\\makestandardbackmatter\{' "$MAIN_TEX" \
    | head -1 \
    | sed -E 's|^\\makestandardbackmatter\{([^}]+)\}.*|\1|' || true)"
  if [[ -n "$BACKMATTER_BIB" ]]; then
    BIBSTYLE_LINE='\bibliographystyle{abbrvnat}'
    BIBLIO_LINE="\\bibliography{${BACKMATTER_BIB}}"
  fi
fi

mkdir -p "$OUT_DIR"

WRAPPER="$BOOK_DIR/_ch_${BASE}.tex"
{
  echo "% Generated by tools/build_local_pdf.sh -- do not edit, do not commit"
  echo "$PREAMBLE"
  echo '\begin{document}'
  echo '\makestandardfrontmatter'
  echo '\mainmatter'
  echo "\\input{chapters/${BASE}.tex}"
  if [[ -n "$BIBSTYLE_LINE" ]]; then echo "$BIBSTYLE_LINE"; fi
  if [[ -n "$BIBLIO_LINE" ]];  then echo "$BIBLIO_LINE";  fi
  echo '\end{document}'
} > "$WRAPPER"

# LECTURENOTES_AUTOBUILD_CHAPTERS=1 keeps tools/latexmkrc.shared from
# regenerating chapter_versions.tex and from re-entering the chapter build.
( cd "$BOOK_DIR" && LECTURENOTES_AUTOBUILD_CHAPTERS=1 latexmk -pdf \
    -interaction=nonstopmode -f -outdir="local" "_ch_${BASE}.tex" \
    >/dev/null 2>&1 ) || true

rm -f "$WRAPPER"

if [[ -f "$OUT_DIR/_ch_${BASE}.pdf" ]]; then
  mv -f "$OUT_DIR/_ch_${BASE}.pdf" "$OUT_DIR/${BASE}.pdf"
  echo "  built  local/${BASE}.pdf"
else
  echo "  FAILED ${BASE} (see ${OUT_DIR}/_ch_${BASE}.log)" >&2
  exit 1
fi
