#!/usr/bin/env bash
# Build one PDF per unit for a beamer slide deck.
# Usage: tools/build_unit_pdfs.sh <slides_dir> [unit_basename]
#
# The slide-deck analogue of build_chapter_pdfs.sh. For each unit*.tex that
# the master deck \input's (or only the named one), this script generates a
# tiny wrapper .tex in the slides directory that reuses the master's preamble
# verbatim, opens on the title slide, then inputs just that unit inside its
# own refsection, and runs latexmk to produce a PDF in <slides_dir>/unit_pdfs/.
#
# Each unit is already a self-contained refsection ending in a References
# frame (\printbibliography), so citation numbering restarts at [1] per unit
# PDF, exactly as in the full deck.
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 <slides_dir> [unit_basename]" >&2
  exit 2
fi

SLIDES_DIR="$(cd "$1" && pwd)"
ONLY_UNIT="${2:-}"
MAIN_TEX="$SLIDES_DIR/disciplined_vibe.tex"
OUT_DIR="$SLIDES_DIR/unit_pdfs"

if [[ ! -f "$MAIN_TEX" ]]; then
  echo "Master deck not found: $MAIN_TEX" >&2
  exit 1
fi

# Pull the preamble out of the master .tex: everything up to (but not
# including) \begin{document}. The wrapper reuses it verbatim so package
# loads, custom commands (\slidesources, \gcmd, cmdtable, ...), the theme,
# and the biblatex/refsection setup all stay in sync automatically.
preamble_end_line=$(grep -n '^\\begin{document}' "$MAIN_TEX" | head -1 | cut -d: -f1)
if [[ -z "$preamble_end_line" ]]; then
  echo "Could not find \\begin{document} in $MAIN_TEX" >&2
  exit 1
fi
PREAMBLE="$(sed -n "1,$((preamble_end_line - 1))p" "$MAIN_TEX")"

# Which units does the master actually build? Take the \input'd unit files
# that are NOT commented out, so this script tracks the deck's live contents.
# (while-read instead of mapfile, so this runs on the stock macOS bash 3.2.)
ACTIVE_UNITS=()
while IFS= read -r unit; do
  [[ -n "$unit" ]] && ACTIVE_UNITS+=("$unit")
done < <(
  grep -E '^\s*\\begin\{refsection\}\\input\{unit[^}]+\}' "$MAIN_TEX" \
    | sed -E 's|.*\\input\{(unit[^}]+)\.tex\}.*|\1|'
)

if [[ ${#ACTIVE_UNITS[@]} -eq 0 ]]; then
  echo "No active \\input{unit...} lines found in $MAIN_TEX" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

build_one() {
  local base="$1"
  local unit_file="$SLIDES_DIR/${base}.tex"
  if [[ ! -f "$unit_file" ]]; then
    echo "skip: $base (no $unit_file)" >&2
    return 0
  fi

  local wrapper="$SLIDES_DIR/_unit_${base}.tex"
  {
    echo "% Generated by tools/build_unit_pdfs.sh -- do not edit, do not commit"
    echo "$PREAMBLE"
    echo '\begin{document}'
    echo '\begin{frame}[plain]\titlepage\end{frame}'
    echo "\\begin{refsection}\\input{${base}.tex}\\end{refsection}"
    echo '\end{document}'
  } > "$wrapper"

  echo ">> building $base"
  ( cd "$SLIDES_DIR" && latexmk -interaction=nonstopmode -halt-on-error "_unit_${base}.tex" >/dev/null 2>&1 ) || {
    echo "  latexmk failed for $base (see $SLIDES_DIR/_unit_${base}.log)" >&2
    return 1
  }

  mv "$SLIDES_DIR/_unit_${base}.pdf" "$OUT_DIR/${base}.pdf"
  echo "  -> unit_pdfs/${base}.pdf"

  # Remove the wrapper source and every build artifact it produced
  # (_unit_<base>.tex/.aux/.bbl/.nav/.snm/.synctex.gz/...); keep only the PDF.
  rm -f "$SLIDES_DIR/_unit_${base}".*
}

status=0
for base in "${ACTIVE_UNITS[@]}"; do
  if [[ -n "$ONLY_UNIT" && "$base" != "$ONLY_UNIT" ]]; then
    continue
  fi
  build_one "$base" || status=1
done

exit "$status"
