#!/usr/bin/env bash
# Build a single-chapter draft wrapper for fast iteration.
# Usage: tools/draft.sh <book_dir> <chapter_basename>
#
# Writes <book_dir>/draft.tex which clones the main file's preamble and
# inputs only the named chapter, so you can latexmk draft.tex (or hit
# build in your IDE) and get a fast PDF of just that chapter without
# rebuilding the whole book or the chapter_pdfs/ pipeline.
#
# To switch chapters, re-run with a different basename.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <book_dir> <chapter_basename>" >&2
  echo "Example: $0 lecturenotes/notes_missingsemester 04_model_integration" >&2
  exit 2
fi

BOOK_DIR="$(cd "$1" && pwd)"
CHAPTER="$2"
BOOK_NAME="$(basename "$BOOK_DIR")"
MAIN_TEX="$BOOK_DIR/$BOOK_NAME.tex"
CHAPTER_TEX="$BOOK_DIR/chapters/${CHAPTER}.tex"
DRAFT_TEX="$BOOK_DIR/draft.tex"

if [[ ! -f "$MAIN_TEX" ]]; then
  echo "Main file not found: $MAIN_TEX" >&2
  exit 1
fi
if [[ ! -f "$CHAPTER_TEX" ]]; then
  echo "Chapter file not found: $CHAPTER_TEX" >&2
  exit 1
fi

preamble_end_line=$(grep -n '^\\begin{document}' "$MAIN_TEX" | head -1 | cut -d: -f1)
if [[ -z "$preamble_end_line" ]]; then
  echo "Could not find \\begin{document} in $MAIN_TEX" >&2
  exit 1
fi
PREAMBLE="$(sed -n "1,$((preamble_end_line - 1))p" "$MAIN_TEX")"

# Reuse the main file's bibliography setup so cites resolve.
BIBSTYLE_LINE="$(grep -E '^\\bibliographystyle' "$MAIN_TEX" | head -1 || true)"
BIBLIO_LINE="$(grep -E '^\\bibliography\{' "$MAIN_TEX" | head -1 || true)"
if [[ -z "$BIBLIO_LINE" ]]; then
  BACKMATTER_BIB="$(grep -E '^\\makestandardbackmatter\{' "$MAIN_TEX" \
    | head -1 \
    | sed -E 's|^\\makestandardbackmatter\{([^}]+)\}.*|\1|' || true)"
  if [[ -n "$BACKMATTER_BIB" ]]; then
    BIBSTYLE_LINE='\bibliographystyle{abbrvnat}'
    BIBLIO_LINE="\\bibliography{${BACKMATTER_BIB}}"
  fi
fi

{
  echo "% Generated by tools/draft.sh -- transient, do not commit."
  echo "% Re-run tools/draft.sh to switch chapters or refresh the preamble."
  echo "$PREAMBLE"
  echo '\begin{document}'
  echo '\mainmatter'
  echo "\\input{chapters/${CHAPTER}.tex}"
  if [[ -n "$BIBSTYLE_LINE" ]]; then echo "$BIBSTYLE_LINE"; fi
  if [[ -n "$BIBLIO_LINE" ]];  then echo "$BIBLIO_LINE";  fi
  echo '\end{document}'
} > "$DRAFT_TEX"

echo "Wrote $DRAFT_TEX (chapter: $CHAPTER)"
echo "Build with: ( cd \"$BOOK_DIR\" && latexmk -pdf draft.tex )"
echo "or open draft.tex in your IDE and hit build."
