#!/usr/bin/env bash
# Generate <book>/chapter_versions.tex from git history.
# Usage: tools/update_chapter_versions.sh <book_dir>
#
# For each chapters/*.tex file, the script extracts the most recent commit's
# short hash and date that touched that file, derives a deterministic
# adjective/fruit/Tier triple from the hash, and writes one
# \setchapterversion{key}{date}{name} line per chapter into
# <book_dir>/chapter_versions.tex. The full book and each per-chapter
# wrapper input that file in their preamble.
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <book_dir>" >&2
  exit 2
fi

BOOK_DIR="$(cd "$1" && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORDS_DIR="$SCRIPT_DIR/words"
OUT="$BOOK_DIR/chapter_versions.tex"
REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ ! -d "$BOOK_DIR/chapters" ]]; then
  echo "No chapters/ directory in $BOOK_DIR" >&2
  exit 1
fi

today="$(date +%Y-%m-%d)"

{
  echo "% generated by tools/update_chapter_versions.sh -- do not edit"
  for f in "$BOOK_DIR"/chapters/*.tex; do
    [[ -e "$f" ]] || continue
    base="$(basename "$f" .tex)"
    rel="${f#$REPO_ROOT/}"

    hash="$(git -C "$REPO_ROOT" log -1 --format='%h' -- "$rel" 2>/dev/null || true)"
    date="$(git -C "$REPO_ROOT" log -1 --format='%ad' --date=short -- "$rel" 2>/dev/null || true)"

    if [[ -z "$hash" ]]; then
      # File has never been committed; mark as uncommitted with today's date.
      hash="local"
      date="$today"
      name="local draft"
    else
      name="$(python3 "$SCRIPT_DIR/version_word.py" "$hash" \
        "$WORDS_DIR/adjectives.txt" \
        "$WORDS_DIR/fruits.txt" \
        "$WORDS_DIR/tiere.txt")"
    fi

    printf '\\setchapterversion{%s}{%s}{%s}\n' "$base" "$date" "$name"
  done
} > "$OUT"

echo "Wrote $OUT"
