#!/usr/bin/env bash
# Generate <book>/chapter_versions.tex from git history.
# Usage: tools/update_chapter_versions.sh <book_dir>
#
# For each chapters/*.tex file, the script extracts the most recent commit's
# short hash and date that touched that file, derives a deterministic
# adjective/fruit/Tier triple from the hash, and writes one
# \setchapterversion{key}{date}{name} line per chapter into
# <book_dir>/chapter_versions.tex. The full book and each per-chapter
# wrapper input that file in their preamble.
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <book_dir>" >&2
  exit 2
fi

BOOK_DIR="$(cd "$1" && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORDS_DIR="$SCRIPT_DIR/words"
OUT="$BOOK_DIR/chapter_versions.tex"
REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ ! -d "$BOOK_DIR/chapters" ]]; then
  echo "No chapters/ directory in $BOOK_DIR" >&2
  exit 1
fi

today="$(date +%Y-%m-%d)"

stamp_for() {
  # Derive a (date, name) stamp from the most recent commit touching the
  # given path. Falls back to today + "local draft" if no commit yet.
  local target_rel="$1"
  local hash date name
  hash="$(git -C "$REPO_ROOT" log -1 --format='%h' -- "$target_rel" 2>/dev/null || true)"
  date="$(git -C "$REPO_ROOT" log -1 --format='%ad' --date=short -- "$target_rel" 2>/dev/null || true)"
  if [[ -z "$hash" ]]; then
    date="$today"
    name="local draft"
  else
    name="$(python3 "$SCRIPT_DIR/version_word.py" "$hash" \
      "$WORDS_DIR/adjectives.txt" \
      "$WORDS_DIR/fruits.txt" \
      "$WORDS_DIR/tiere.txt")"
  fi
  printf '%s\t%s\n' "$date" "$name"
}

{
  echo "% generated by tools/update_chapter_versions.sh -- do not edit"

  # Book-level stamp: most recent commit anywhere under the book directory.
  # Used by \printbookversion on the copyright page.
  book_rel="${BOOK_DIR#$REPO_ROOT/}"
  IFS=$'\t' read -r book_date book_name < <(stamp_for "$book_rel")
  printf '\\setbookversion{%s}{%s}\n' "$book_date" "$book_name"

  for f in "$BOOK_DIR"/chapters/*.tex; do
    [[ -e "$f" ]] || continue
    base="$(basename "$f" .tex)"
    rel="${f#$REPO_ROOT/}"
    IFS=$'\t' read -r ch_date ch_name < <(stamp_for "$rel")
    printf '\\setchapterversion{%s}{%s}{%s}\n' "$base" "$ch_date" "$ch_name"
  done
} > "$OUT"

echo "Wrote $OUT"
